### ISSUE TITLE
Plugin fails to run cantiliver snap fit creation after creating one in a discarded document

### ISSUE THREAD

**Issue by drphil3d** [AlfMikael/snap-generator#1]
This happens when I run the plugin in a blank file, close the file without saving then run the command again.

Failed:
Traceback (most recent call last):
  File "/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/snap-generator-v0.1.1-alpha\commands\CantileverCommand.py", line 31, in build
    rootComp = design.rootComponent
  File "/AppData/Local/Autodesk/webdeploy/production/2719e3c6bed8896e3c7319fbb8bfbceff8f489a4/Api/Python/packages\adsk\fusion.py", line 16125, in _get_rootComponent
    return _fusion.Design__get_rootComponent(self)
RuntimeError: 4 : An API Object refers to a deleted Object

**Comment by AlfMikael** [comment]
The bug has been found at a fix has been committed to the master branch.

Thanks a lot for the feedback!
